version: '3.8'

services:
  sonarqube:
    image: sonarqube:10.3-community
    restart: unless-stopped
    container_name: sonarqube
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '9000:9000'
    env_file: .env.sonar.v1
    depends_on:
      sonardb:
        condition: service_healthy
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonardb:
    image: postgres:13-alpine
    container_name: sonardb
    restart: unless-stopped
    env_file: .env.sonar.v1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    name: sonarnet
    external: true

volumes:
  sonar_conf:
  sonar_data:
  sonar_extensions:
  sonar_bundled-plugins:
  db_data:
